# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180328_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
