# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180604_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingchart',
            name='name',
        ),
        migrations.AddField(
            model_name='shopingchart',
            name='code',
            field=models.CharField(default='', max_length=300),
        ),
    ]
