# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendiente de pago'), (2, 'Cancelado'), (3, 'Pagado'), (4, 'En preparaci\xf3n'), (5, 'Enviado'), (6, 'Entregado')], default=1),
        ),
    ]
