# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='album', max_length=50)),
                ('slug', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='header_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='/image.jpg', upload_to='photos'),
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Album'),
        ),
        migrations.AddField(
            model_name='product',
            name='album',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Album'),
        ),
    ]
